/**
 * Per-tool agent tips for the typewriter animation on tool pages.
 * Each tool has 10-20 unique, relevant tips that cycle randomly.
 * Falls back to a general set for tools without specific tips.
 */

export const TOOL_TIPS: Record<string, string[]> = {
  'hook-generator': [
    "Curiosity beats information in the first 3 seconds.",
    "Promise transformation, not features.",
    "Great hooks create open loops the brain must close.",
    "Challenge a common assumption your audience holds.",
    "Use numbers — they signal specificity and value.",
    "Start with a question your audience secretly asks.",
    "Negative hooks ('Stop doing X') often outperform positive ones.",
    "The best hooks make viewers feel they're missing out.",
    "Keep hooks under 12 words for maximum impact.",
    "Contrast creates tension — before vs. after works.",
    "Personal stories outperform generic advice.",
    "A great hook promises the payoff but delays the reveal.",
    "Use power words: secret, hidden, banned, exposed.",
    "Test 5+ hooks per video — never settle for the first.",
    "Your hook should make viewers uncomfortable with not knowing.",
    "Specificity beats vagueness: '5 hacks' > 'some hacks'.",
    "Emotional hooks travel further than logical ones.",
    "The hook is 80% of whether your video gets clicked.",
    "Contrarian opinions drive engagement and shares.",
    "Ask yourself: would I click this hook?",
  ],
  'ai-writer': [
    "Better prompts create better writing.",
    "Give AI more context about your audience and goal.",
    "Mention your desired tone explicitly.",
    "Provide examples of writing you admire.",
    "Edit AI output — never publish raw generation.",
    "Use constraints: word count, reading level, format.",
    "Ask AI to write 3 versions, then pick the best.",
    "Feed AI your previous content for voice matching.",
    "Specify the platform — blog reads differently than social.",
    "Always fact-check AI-generated statistics.",
    "Use AI for outlines, then write the final draft yourself.",
    "Tell AI what NOT to do — constraints improve output.",
    "Rewrite AI content in your own voice for authenticity.",
    "Ask AI to explain its reasoning for better transparency.",
    "Use AI for first drafts, human for final polish.",
    "Break long requests into smaller, focused prompts.",
    "Specify your expertise level for appropriate complexity.",
    "Ask AI to critique its own writing.",
    "Use temperature settings to control creativity.",
    "Save effective prompts in your Prompt Library.",
  ],
  'title-optimizer': [
    "Numbers in titles increase CTR by 36% on average.",
    "Titles under 60 characters avoid truncation in search.",
    "Use power words: ultimate, proven, essential, secret.",
    "Ask a question — questions drive curiosity clicks.",
    "Test emotional vs. logical titles for your niche.",
    "Front-load important keywords for search visibility.",
    "Avoid clickbait — deliver on your title's promise.",
    "Use brackets [Video] or (2025) for extra context.",
    "A/B test titles — even small changes can double CTR.",
    "Negative titles ('Mistakes to avoid') often outperform positive.",
    "Keep titles readable at a glance on mobile.",
    "Use colons for subtitle-style titles: Main: Subtitle.",
    "Seasonal titles get a CTR boost during trends.",
    "Your title should match the thumbnail's message.",
    "Avoid generic titles like 'My experience with X'.",
    "Use odd numbers — they perform better than even.",
    "Include the year for evergreen content freshness.",
    "Test 10+ titles per video before publishing.",
    "Emotional triggers: shocking, heartbreaking, hilarious.",
    "The title is 50% of your click-through decision.",
  ],
  'script-writer': [
    "Hook viewers within the first 5 seconds.",
    "Keep paragraphs conversational and short.",
    "Build curiosity every 60 seconds to prevent drop-off.",
    "Use pattern interrupts to re-engage attention.",
    "Write for the ear, not the eye — read scripts aloud.",
    "Every section should have a clear payoff.",
    "Cut filler words — every sentence must earn its place.",
    "Use the AIDA framework: Attention, Interest, Desire, Action.",
    "End with a strong CTA that feels natural.",
    "Storytelling beats information dumps every time.",
    "Use open loops — introduce questions, answer later.",
    "Vary sentence length for rhythm and pacing.",
    "Write b-roll cues into your script for editing.",
    "The last 30 seconds determine whether viewers return.",
    "Use 'you' more than 'I' — make it about the viewer.",
    "Plan your thumbnail and title before writing the script.",
    "Include emotional peaks every 2-3 minutes.",
    "Scripts should be 130-150 words per minute of video.",
    "Never start with 'Hey guys' — start with the hook.",
    "Read your script out loud to catch awkward phrasing.",
  ],
  'thumbnail-analyzer': [
    "Faces attract 38% more attention than text-only thumbnails.",
    "High contrast between subject and background improves CTR.",
    "Keep text under 4 words — less is more.",
    "Use the rule of thirds for composition.",
    "Bright, saturated colors outperform muted ones.",
    "Test thumbnails at 1280x720 — that's what viewers see.",
    "Yellow and red are the highest-CTR accent colors.",
    "Show emotion on faces — shock and surprise work best.",
    "Avoid clutter — one focal point per thumbnail.",
    "Use arrows or circles to direct the viewer's eye.",
    "Thumbnails with text on the right perform better on mobile.",
    "Dark backgrounds make subjects pop more.",
    "Consistent thumbnail style builds channel recognition.",
    "A/B test thumbnails with YouTube's new test feature.",
    "Your thumbnail should tell a story without the title.",
    "Use custom fonts — default fonts look generic.",
    "Zoom in on faces — they're more visible at small sizes.",
    "Contrast warm and cool colors for visual tension.",
    "Avoid using more than 3 colors per thumbnail.",
    "Check thumbnails in grayscale — if it works, color will too.",
  ],
  'repurpose-engine': [
    "One great video should become 10+ pieces of content.",
    "Extract key quotes for Twitter threads.",
    "Turn blog posts into LinkedIn carousels.",
    "Convert long videos into 3-5 short-form clips.",
    "Repurpose podcast transcripts into blog articles.",
    "Use the same core idea across 5 platforms with different angles.",
    "Repurposing saves 80% of content creation time.",
    "Adapt tone for each platform — LinkedIn ≠ TikTok.",
    "Extract data points for infographic-style posts.",
    "Turn FAQs into standalone educational content.",
    "Repurpose evergreen content every 3-6 months.",
    "Use video transcripts for SEO blog content.",
    "Transform webinars into email courses.",
    "Clip the most engaging 30 seconds for Reels.",
    "Create a content calendar from one brainstorm session.",
    "Turn customer questions into tutorial content.",
    "Repurpose testimonials into social proof posts.",
    "Use the same story across platforms with different formats.",
    "Extract the best insight for a quote graphic.",
    "Never create from scratch when you can repurpose.",
  ],
  'invoice-generator': [
    "Always specify payment terms clearly — Net 30 is standard.",
    "Include late payment fees to encourage on-time payment.",
    "Use sequential invoice numbers for professional tracking.",
    "Add your logo and brand colors for consistency.",
    "Specify the scope of work to prevent disputes.",
    "Include multiple payment methods for convenience.",
    "Send invoices immediately after delivering work.",
    "Add a 'thank you' note to build client relationships.",
    "Clearly list deliverables and quantities.",
    "Include your tax ID for proper accounting.",
    "Use professional templates — not handwritten invoices.",
    "Follow up on unpaid invoices within 7 days.",
    "Offer early payment discounts (2/10 Net 30).",
    "Keep copies of all invoices for tax purposes.",
    "Include a purchase order number if applicable.",
    "Specify currency clearly for international clients.",
    "Add a payment deadline, not just 'Net 30'.",
    "Use automated reminders for overdue invoices.",
    "Track which clients pay late — adjust terms accordingly.",
    "A clear invoice reduces payment delays by 40%.",
  ],
  'content-calendar': [
    "Consistency builds trust with the algorithm.",
    "Batch content creation to avoid burnout.",
    "Plan 4 weeks ahead minimum for consistent publishing.",
    "Post at the same time each day for audience habits.",
    "Leave buffer days for unexpected delays.",
    "Align content with trending topics and seasons.",
    "Use themes for each day: Tutorial Tuesday, Feature Friday.",
    "Schedule evergreen content to fill gaps.",
    "Track which days get the most engagement.",
    "Repurpose old content to fill calendar gaps.",
    "Plan series content 2-3 months in advance.",
    "Color-code by content type for visual clarity.",
    "Include holidays and industry events in your calendar.",
    "Set reminders 24 hours before publishing.",
    "Review your calendar weekly and adjust based on performance.",
    "Never publish without a content calendar.",
    "Plan rest days — consistency doesn't mean daily posting.",
    "Use analytics to find your best posting times.",
    "Cross-post on multiple platforms on the same day.",
    "A content calendar reduces last-minute panic by 90%.",
  ],
};

// General tips for tools without specific tips
const GENERAL_TIPS = [
  "Specificity is the key to good AI outputs.",
  "Give context before asking AI to generate content.",
  "Always review and edit AI-generated content.",
  "Save effective prompts in your Prompt Library.",
  "Test multiple variations to find the best result.",
  "Use constraints to force better AI responses.",
  "Provide examples of what you want.",
  "Break complex tasks into smaller steps.",
  "Mention your audience for more targeted output.",
  "Specify your desired tone and style.",
  "Use the results as a starting point, not the final version.",
  "Iterate — refine your inputs based on outputs.",
  "Save your best generations to the Library.",
  "Use the analysis section to understand why results work.",
  "Higher scores indicate stronger, more engaging content.",
];

/**
 * Get tips for a specific tool. Falls back to general tips.
 */
export function getToolTips(toolId: string): string[] {
  return TOOL_TIPS[toolId] ?? GENERAL_TIPS;
}

/**
 * Get a random tip from a tool's tip set.
 */
export function getRandomTip(toolId: string): string {
  const tips = getToolTips(toolId);
  return tips[Math.floor(Math.random() * tips.length)];
}
